apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9092
  selector:
    app: {{ include "kafka.name" . }}
