replicaCount: 3

image:
  repository: bitnami/cassandra
  tag: 4.1.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9042

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

storage:
  size: 10Gi
  className: ""

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
