apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassandra.fullname" . }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      name: cql
  selector:
    app: {{ include "cassandra.name" . }}
