replicaCount: 1

image:
  repository: bitnami/kafka
  tag: 3.6.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9092

persistence:
  enabled: true
  size: 8Gi

zookeeper:
  enabled: true
  replicaCount: 1
  image:
    repository: bitnami/zookeeper
    tag: 3.9.1

resources: {}
